version: '3'

services:
  app:
    image: challenge-xss
    build: challenge/app
    ports:
      - 9110:3000
    environment:
      FLAG: Securinets{FAKE}
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
    networks:
      - internal
    depends_on:
      - bot
    container_name: challenge-xss-app
    deploy:
      resources:
        limits:
          memory: 1G
  bot:
    image: challenge-xss-bot
    build: challenge/bot
    ports:
      - 9111:3000
    environment:
      APPNAME: Admin Bot
      APPLIMIT: 2
      APPLIMITTIME: 60
      USE_PROXY: 1
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - internal
    container_name: challenge-xss-bot

networks:
  internal:
