version: '3'
services:
  challenge:
    container_name: quantum_quiz
    build:
      context: ./challenge
      dockerfile: Dockerfile
    ports:
      - 11001:1337
    read_only: true
    cap_drop:
      - all
    restart: on-failure
