version: '3'
services:
  challenge:
    container_name: ret2libc
    build:
      context: ./main
      dockerfile: Dockerfile
    ports:
      - 11003:10001
    read_only: true
    cap_drop:
      - all
              
    restart: on-failure
