version: '3'
services:
  challenge:
    container_name: WarmupFSB
    build:
      context: ./challenge
      dockerfile: Dockerfile
    ports:
      - 12003:1339
    read_only: true
    cap_drop:
      - all
              
    restart: on-failure